### PR TITLE
Add base exception for #61

### PR DESCRIPTION
**Pull request by tulioz**
Add a base exception for normalize so that end users have a clear catchall exception to catch and handle.

### CODE REVIEW

**Comment by rogerhu** [comment]
You are awesome ofer

**Comment by rogerhu** [comment]
Lgtm @asher we can get rid of that generic exception catcher in data warehouse stuff

**Comment by rbm** [comment]
lgtm

**Comment by dhui** [comment]
Love the unittest!
:shipit:

**Pull request merged**
